import React,{useEffect,useRef,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {Sprout,LayoutDashboard,Scan,MapPin,Radio,History,BarChart3,ShieldAlert,FlaskConical,ChevronDown,Menu,X,LogOut,Check,Play,Sliders,Database,BrainCircuit,Languages} from 'lucide-react';
import {api} from '../services/api';
import {useLanguage,Lang} from '../i18n';
interface NavbarProps{currentRole?:string|null;onLogout?:()=>void;onRoleChange?:(role:string)=>void}
export const Navbar:React.FC<NavbarProps>=({currentRole='FARMER',onLogout,onRoleChange})=>{
 const location=useLocation();const {lang,setLang,t}=useLanguage();const [healthStatus,setHealthStatus]=useState<'ONLINE'|'OFFLINE'>('ONLINE');const [latencyMs,setLatencyMs]=useState<number|null>(14);const [mobileMenuOpen,setMobileMenuOpen]=useState(false);const [userMenuOpen,setUserMenuOpen]=useState(false);const [operationsDropdownOpen,setOperationsDropdownOpen]=useState(false);const userMenuRef=useRef<HTMLDivElement>(null);const operationsMenuRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{let mounted=true;const check=async()=>{const start=performance.now();try{await api.getHealth();if(mounted){setHealthStatus('ONLINE');setLatencyMs(Math.round(performance.now()-start));}}catch{if(mounted){setHealthStatus('OFFLINE');setLatencyMs(null);}}};check();const id=setInterval(check,8000);return()=>{mounted=false;clearInterval(id)}},[]);
 useEffect(()=>{const onOutside=(event:MouseEvent)=>{if(userMenuRef.current&&!userMenuRef.current.contains(event.target as Node))setUserMenuOpen(false);if(operationsMenuRef.current&&!operationsMenuRef.current.contains(event.target as Node))setOperationsDropdownOpen(false)};document.addEventListener('mousedown',onOutside);return()=>document.removeEventListener('mousedown',onOutside)},[]);
 useEffect(()=>{setMobileMenuOpen(false);setUserMenuOpen(false);setOperationsDropdownOpen(false)},[location.pathname]);
 const primary=[{path:'/',label:t('overview'),icon:LayoutDashboard},{path:'/intelligence',label:t('intelligence'),icon:BrainCircuit},{path:'/scan',label:t('scan'),icon:Scan},{path:'/map',label:t('map'),icon:MapPin}];
 const operationItems=[{path:'/sprayer',label:t('sprayer'),desc:'ESP32',icon:Radio},{path:'/storage',label:t('storage'),desc:'Stock',icon:FlaskConical},{path:'/history',label:t('history'),desc:'Records',icon:History},{path:'/analytics',label:t('analytics'),desc:'ROI',icon:BarChart3},{path:'/audit',label:t('audit'),desc:'Logs',icon:ShieldAlert},{path:'/admin/knowledge',label:t('knowledge'),desc:'AI rules',icon:Database}];
 const isOperationActive=operationItems.some(item=>location.pathname===item.path);
 return <header className="sticky top-0 z-40 bg-zinc-950/90 backdrop-blur-xl border-b border-emerald-500/10 shadow-[0_4px_24px_rgba(0,0,0,0.35)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-16 gap-3"><Link to="/" className="flex items-center space-x-2.5 shrink-0"><div className="w-9 h-9 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-white"><Sprout className="w-4 h-4"/></div><span className="font-extrabold text-white text-base tracking-tight">AgriPrescribe</span></Link>
 <nav className="hidden lg:flex items-center space-x-1">{primary.map(item=>{const I=item.icon;const active=location.pathname===item.path;return <Link key={item.path} to={item.path} className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition ${active?'bg-emerald-950/50 text-emerald-300 border border-emerald-500/20':'text-zinc-400 hover:text-white hover:bg-zinc-900'}`}><I className="w-3.5 h-3.5"/>{item.label}</Link>})}<div className="relative" ref={operationsMenuRef}><button onClick={()=>setOperationsDropdownOpen(!operationsDropdownOpen)} className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium ${isOperationActive?'bg-emerald-950/50 text-emerald-300 border border-emerald-500/20':'text-zinc-400 hover:text-white hover:bg-zinc-900'}`}><Sliders className="w-3.5 h-3.5"/>{t('operations')}<ChevronDown className="w-3 h-3"/></button>{operationsDropdownOpen&&<div className="absolute top-full left-0 mt-2 w-72 rounded-xl bg-zinc-900 border border-zinc-800 shadow-2xl p-2 z-50">{operationItems.map(item=>{const I=item.icon;return <Link key={item.path} to={item.path} className="flex items-center gap-3 p-2.5 rounded-lg hover:bg-zinc-800"><I className="w-4 h-4 text-emerald-400"/><div><div className="text-xs font-semibold text-zinc-100">{item.label}</div><div className="text-[11px] text-zinc-500">{item.desc}</div></div></Link>})}</div>}</div></nav>
 <div className="flex items-center gap-2"><label className="language-switcher"><Languages className="w-4 h-4"/><select value={lang} onChange={e=>setLang(e.target.value as Lang)} aria-label={t('language')}><option value="en">English</option><option value="hi">हिन्दी</option><option value="ml">മലയാളം</option></select></label><Link to="/demo" className="hidden sm:flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold bg-emerald-600 text-white"><Play className="w-3.5 h-3.5"/>{t('demo')}</Link><div className="hidden md:flex items-center gap-2 px-2.5 py-1.5 rounded-lg bg-zinc-900 border border-zinc-800 text-[11px] text-zinc-400"><span className={`w-2 h-2 rounded-full ${healthStatus==='ONLINE'?'bg-emerald-500':'bg-rose-500'}`}/><span>{healthStatus==='ONLINE'?`${t('online')} • ${latencyMs??0}ms`:t('offline')}</span></div><div className="relative" ref={userMenuRef}><button onClick={()=>setUserMenuOpen(!userMenuOpen)} className="flex items-center gap-2 p-1.5 rounded-lg hover:bg-zinc-800"><div className="w-8 h-8 rounded-full bg-zinc-800 border border-zinc-700 flex items-center justify-center text-xs font-bold">{currentRole?.[0]||'U'}</div><ChevronDown className="w-3.5 h-3.5 text-zinc-400 hidden sm:block"/></button>{userMenuOpen&&<div className="absolute right-0 mt-2 w-52 rounded-xl bg-zinc-900 border border-zinc-800 shadow-xl p-1 z-50"><div className="px-3 py-2 border-b border-zinc-800 text-xs text-zinc-400">{t('role')}: <span className="text-zinc-200">{currentRole}</span></div>{['FARMER','AGRONOMIST','ADMIN'].map(role=><button key={role} onClick={()=>{onRoleChange?.(role);setUserMenuOpen(false)}} className="w-full px-2 py-2 text-left text-xs rounded-lg hover:bg-zinc-800 flex justify-between text-zinc-300">{role}{currentRole===role&&<Check className="w-3.5 h-3.5 text-emerald-400"/>}</button>)}<button onClick={()=>onLogout?.()} className="w-full mt-1 px-2 py-2 text-left text-xs rounded-lg text-rose-300 flex gap-2 border-t border-zinc-800"><LogOut className="w-3.5 h-3.5"/>{t('signout')}</button></div>}</div><button onClick={()=>setMobileMenuOpen(!mobileMenuOpen)} className="p-2 rounded-lg lg:hidden text-zinc-300">{mobileMenuOpen?<X className="w-5 h-5"/>:<Menu className="w-5 h-5"/>}</button></div></div>{mobileMenuOpen&&<div className="lg:hidden py-3 border-t border-zinc-800 space-y-1">{[...primary,...operationItems].map(item=>{const I=item.icon;return <Link key={item.path} to={item.path} className="flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm text-zinc-300 hover:bg-zinc-900"><I className="w-4 h-4 text-emerald-400"/>{item.label}</Link>})}</div>}</div></header>;
};
