import React,{createContext,useContext,useEffect,useMemo,useRef,useState} from 'react';
export type Lang='en'|'hi'|'ml';
const dict:Record<Lang,Record<string,string>>={
 en:{overview:'Overview',intelligence:'Intelligence',scan:'Plant Scan',map:'Farm Map',operations:'Operations',demo:'Demo',role:'Role',signout:'Sign Out',sprayer:'Sprayer Control & Missions',storage:'Chemical Storage & Stock',history:'Spray Mission History',analytics:'Analytics & ROI',audit:'Compliance & Audit Logs',knowledge:'Knowledge Base Admin',field:'Field',weather:'Weather',healthy:'Healthy',monitor:'Monitor',startScan:'Scan a plant',openMap:'Open farm map',checkWeather:'Check weather',controlSprayer:'Sprayer controls',farmerHelp:'Farmer quick actions',language:'Language',online:'ONLINE',offline:'OFFLINE'},
 hi:{overview:'मुख्य पृष्ठ',intelligence:'स्मार्ट सलाह',scan:'पौधे की जाँच',map:'खेत का नक्शा',operations:'कार्य',demo:'डेमो',role:'भूमिका',signout:'साइन आउट',sprayer:'स्प्रे मशीन नियंत्रण',storage:'रसायन भंडार',history:'स्प्रे इतिहास',analytics:'बचत व आँकड़े',audit:'रिकॉर्ड व अनुपालन',knowledge:'ज्ञान आधार',field:'खेत',weather:'मौसम',healthy:'स्वस्थ',monitor:'निगरानी',startScan:'पौधे की फोटो लें',openMap:'खेत का नक्शा देखें',checkWeather:'मौसम देखें',controlSprayer:'स्प्रे मशीन',farmerHelp:'किसान के लिए आसान विकल्प',language:'भाषा',online:'ऑनलाइन',offline:'ऑफलाइन'},
 ml:{overview:'പ്രധാന പേജ്',intelligence:'സ്മാർട്ട് നിർദ്ദേശം',scan:'ചെടി പരിശോധിക്കുക',map:'കൃഷിയിട മാപ്പ്',operations:'പ്രവർത്തനങ്ങൾ',demo:'ഡെമോ',role:'പങ്ക്',signout:'സൈൻ ഔട്ട്',sprayer:'സ്പ്രെയർ നിയന്ത്രണം',storage:'രാസവസ്തു സംഭരണം',history:'സ്പ്രേ ചരിത്രം',analytics:'ലാഭവും കണക്കുകളും',audit:'രേഖകളും അനുസരണവും',knowledge:'അറിവ് കേന്ദ്രം',field:'കൃഷിയിടം',weather:'കാലാവസ്ഥ',healthy:'ആരോഗ്യമുള്ളത്',monitor:'നിരീക്ഷിക്കുക',startScan:'ചെടിയുടെ ചിത്രം എടുക്കുക',openMap:'കൃഷിയിട മാപ്പ് കാണുക',checkWeather:'കാലാവസ്ഥ പരിശോധിക്കുക',controlSprayer:'സ്പ്രെയർ',farmerHelp:'കർഷകർക്കുള്ള എളുപ്പ വഴികൾ',language:'ഭാഷ',online:'ഓൺലൈൻ',offline:'ഓഫ്‌ലൈൻ'}
};
const phrases:Record<Exclude<Lang,'en'>,Record<string,string>>={
 hi:{'Precision Spraying & Field Operations':'सटीक छिड़काव और खेत प्रबंधन','Chemical Volume Reduction':'रसायन की बचत','Prescription Volume':'अनुशंसित मात्रा','Scanned Plant Foliage':'जाँचे गए पौधे','Sprayer Hardware Node':'स्प्रे मशीन की स्थिति','Foliage Infection & Spray Dosage Breakdown':'फसल स्वास्थ्य और उपचार सारांश','Scan Leaf':'पत्ती की जाँच करें','Launch Demo':'डेमो शुरू करें','Interactive Walkthrough':'आसान प्रदर्शन','Refresh Telemetry':'जानकारी ताज़ा करें','No scan records recorded yet':'अभी कोई पौधा जाँचा नहीं गया','Ready':'तैयार','Connected':'जुड़ा हुआ','Start Mission':'कार्य शुरू करें','Stop Mission':'कार्य रोकें','Treatment History':'उपचार इतिहास','Weather Intelligence':'मौसम आधारित सलाह','Scout Schedule':'खेत निरीक्षण समय','Disease Detection':'रोग पहचान','Upload Image':'फोटो अपलोड करें','Take Photo':'फोटो लें','Save':'सहेजें','Cancel':'रद्द करें','Retry':'फिर कोशिश करें'},
 ml:{'Precision Spraying & Field Operations':'കൃത്യമായ സ്പ്രേയിംഗും കൃഷിയിട നിയന്ത്രണവും','Chemical Volume Reduction':'രാസവസ്തു ലാഭം','Prescription Volume':'നിർദ്ദേശിച്ച അളവ്','Scanned Plant Foliage':'പരിശോധിച്ച ചെടികൾ','Sprayer Hardware Node':'സ്പ്രെയർ നില','Foliage Infection & Spray Dosage Breakdown':'വിള ആരോഗ്യവും ചികിത്സാ സംഗ്രഹവും','Scan Leaf':'ഇല പരിശോധിക്കുക','Launch Demo':'ഡെമോ ആരംഭിക്കുക','Interactive Walkthrough':'ലളിതമായ പ്രദർശനം','Refresh Telemetry':'വിവരം പുതുക്കുക','No scan records recorded yet':'ഇതുവരെ ചെടി പരിശോധിച്ചിട്ടില്ല','Ready':'തയ്യാർ','Connected':'ബന്ധിപ്പിച്ചു','Start Mission':'പ്രവർത്തനം ആരംഭിക്കുക','Stop Mission':'പ്രവർത്തനം നിർത്തുക','Treatment History':'ചികിത്സാ ചരിത്രം','Weather Intelligence':'കാലാവസ്ഥാ നിർദ്ദേശം','Scout Schedule':'കൃഷിയിട പരിശോധന സമയം','Disease Detection':'രോഗം കണ്ടെത്തൽ','Upload Image':'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക','Take Photo':'ചിത്രം എടുക്കുക','Save':'സേവ് ചെയ്യുക','Cancel':'റദ്ദാക്കുക','Retry':'വീണ്ടും ശ്രമിക്കുക'}
};
const C=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(k:string)=>string}>({lang:'en',setLang:()=>{},t:k=>k});
export const LanguageProvider:React.FC<React.PropsWithChildren>=({children})=>{const [lang,setLangState]=useState<Lang>(()=>(localStorage.getItem('appLanguage') as Lang)||'en');const setLang=(l:Lang)=>{localStorage.setItem('appLanguage',l);setLangState(l)};useEffect(()=>{document.documentElement.lang=lang},[lang]);const value=useMemo(()=>({lang,setLang,t:(k:string)=>dict[lang][k]||dict.en[k]||k}),[lang]);return <C.Provider value={value}>{children}</C.Provider>};
export const useLanguage=()=>useContext(C);
export const AutoTranslate:React.FC=()=>{const {lang}=useLanguage();const originals=useRef(new WeakMap<Text,string>());useEffect(()=>{const translateNode=(node:Node)=>{if(node.nodeType===Node.TEXT_NODE){const t=node as Text;const parent=t.parentElement;if(!parent||parent.closest('code,pre,.font-mono,[data-no-translate]'))return;const current=t.nodeValue||'';if(!originals.current.has(t))originals.current.set(t,current);const original=originals.current.get(t)||current;const trimmed=original.trim();if(!trimmed)return;if(lang==='en'){t.nodeValue=original;return}const replacement=phrases[lang][trimmed];if(replacement)t.nodeValue=original.replace(trimmed,replacement);}else node.childNodes.forEach(translateNode)};translateNode(document.body);const observer=new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(translateNode)));observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[lang]);return null};
